#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#https://www.udemy.com/course/the-python-mega-course/
#difflib
#SequenceMatcher
#get_close_matches
#93

import json
import difflib
from difflib import get_close_matches

data = json.load(open('data.json'))

def input_word():
    word = input('Please enter word: ').lower()
    try:
        print(";".join(data[word]))
        input_word()
    except:
        similar = get_close_matches(word,data.keys(),3)
        if len(similar) > 0:
            new_word = ("".join(similar[0]))
            print('Do you mean '+ new_word +'?')
            ans = input('Yes or No? (Y/N)').lower()
            if ans == 'y' or ans == 'yes':
                print(";".join(data[new_word]))
            elif ans == 'n' or ans == 'no':
                new_word = ("".join(similar[1]))
                print('Do you mean ' + new_word + '?')
                ans = input('Yes or No? (Y/N)').lower()
                if ans == 'y' or ans == 'yes':
                    print(";".join(data[new_word]))
                elif ans == 'n' or ans == 'no':
                    new_word = ("".join(similar[2]))
                    print('Do you mean ' + new_word + '?')
                    ans = input('Yes or No? (Y/N)').lower()

                    if ans == 'y' or ans == 'yes':
                        print(";".join(data[new_word]))
                    elif ans == 'n' or ans == 'no':
                        print('The word doesn\'t exist. Please double check.')
                        input_word()
                    else:
                        print('Please try again.')
                        input_word()
                else:
                    print('Please try again.')
                    input_word()


            else:
                print('Please try again.')
                input_word()

input_word()
